### PR TITLE
Use absolute path for template endpoint

### LINKED ISSUE #124: [BUG] Template management fails when AWS IAM authentication is used
**Describe the bug**
Template management fails to install a template when AWS IAM authentication is used. According to the log it fails to construct URL when signing the AWS request.

**To Reproduce**
1. Configure logstash output as follows:
        opensearch {
            auth_type => {
                type => "aws_iam"
                region => "us-west-2"
            }
            id => "Write_Events_To_Elasticsearch"
            hosts => ["https://open_search_instance.us-west-2.es.amazonaws.com"]
            manage_template => true
            template_overwrite => true
            template => "/usr/share/logstash/files/events.json"
            template_name => "events_101"
            sniffing => false
            index => "events_101-%{+YYYY-MM-dd}"
        }
(in my case it takes credentials from the ~/.aws/credentials file, hence they are not specified inside auth_type)
2. Run the pipeline and observe the exception.

**Expected behavior**
Template installed without an error.

**Plugins**
kafka input
opensearch output

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
 - OS: Linux
 - Version 5.4.172-90.336.amzn2.x86_64 x86_64

**Additional context**
Excerpt from the log:

[2022-02-09T18:26:47,670][INFO ][logstash.outputs.opensearch][main] Installing OpenSearch template {:name=>"events_101"}
[2022-02-09T18:26:47,672][ERROR][logstash.outputs.opensearch][main] Failed to install template {
 :message=>"bad component(expected absolute path component): _template/events_101", 
 :exception=>URI::InvalidComponentError, 
 :backtrace=>[
  "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/uri/generic.rb:771:in `check_path'", 
  "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/uri/generic.rb:819:in `path='", 
  "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/uri/generic.rb:193:in `initialize'", 
  "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/uri/generic.rb:138:in `build'", 
  "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/uri/http.rb:62:in `build'", 
  "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch/http_client/manticore_adapter.rb:176:in `sign_aws_request'", 
  "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch/http_client/manticore_adapter.rb:154:in `perform_request'", 
  "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch/http_client/pool.rb:270:in `perform_request_to_url'", 
  "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch/http_client/pool.rb:257:in `block in perform_request'", 
  "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch/http_client/pool.rb:346:in `with_connection'", 
  "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch/http_client/pool.rb:256:in `perform_request'", 
  "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch/http_client/pool.rb:264:in `block in Pool'", 
  "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch/http_client.rb:388:in `template_put'", 
  "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch/http_client.rb:82:in `template_install'", 
  "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch/template_manager.rb:37:in `install'", 
  "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch/template_manager.rb:25:in `install_template'", 
  "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch.rb:412:in `install_template'", 
  "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch.rb:247:in `finish_register'", 
  "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch.rb:224:in `block in register'", 
  "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/plugin_mixins/opensearch/common.rb:83:in `block in after_successful_connection'"
]}

sample template events.json:
    {
    "order": 0,
    "index_patterns": [
        "events_101*"
    ],
    "settings": {
        "index": {
            "codec": "best_compression",
            "mapping": {
                "ignore_malformed": "true"
            },
            "refresh_interval": "30s",
            "analysis": {
                "normalizer": {
                    "lowercase_normalizer": {
                        "filter": [
                            "lowercase"
                        ],
                        "type": "custom",
                        "char_filter": []
                    }
                }
            },
            "number_of_shards": "5",
            "number_of_replicas": "1"
        }
    },
    "mappings": {
        "_doc": {
            "_size": {
                "enabled": true
            },
            "_field_names": {
                "enabled": false
            },
            "dynamic": false,
            "properties": {
                "id": {
                    "norms": false,
                    "index": false,
                    "type": "keyword",
                    "doc_values": false
                },
                "status": {
                    "normalizer": "lowercase_normalizer",
                    "type": "keyword"
                }
            }
        }
    },
    "aliases": {
        "events_101": {},
        "event_101": {}
      }
    }

### LINKED ISSUE #144: [BUG] Cannot install index template
**Describe the bug**
When trying to install an index template using Logstash 7.17 or 8.2 and the opensearch plugin to an AWS Opensearch cluster, we get the following error message:
```
[2022-05-31T14:30:41,259][INFO ][logstash.outputs.opensearch][main] Using mapping template from {:path=>"/etc/logstash/es-templates/finance-reporting-tool-v1.json"}
[2022-05-31T14:30:41,362][WARN ][logstash.outputs.opensearch][main] Restored connection to OpenSearch instance {:url=>"https://search-purestake-main-cluster-u42s23ct42suzqq4dzjd65biga.us-east-2.es.amazonaws.com:443/"}
[2022-05-31T14:30:41,417][INFO ][logstash.outputs.opensearch][main] Installing OpenSearch template {:name=>"finance-reporting-tool-v1"}
[2022-05-31T14:30:41,433][INFO ][logstash.outputs.opensearch][main] Cluster version determined (7.10.2) {:version=>7}
[2022-05-31T14:30:41,449][ERROR][logstash.outputs.opensearch][main] Failed to install template {:message=>"bad component(expected absolute path component): _template/finance-reporting-tool-v1",
```

**To Reproduce**
1. Install logstash 8.2.2 or logstash 7.17.3
2. Install plugin logstash-output-opensearch (1.2.0)
3. Configure an output such as: 
```
  opensearch {
      hosts => ["https://redacted.es.amazonaws.com:443"]
      auth_type => {
        type => 'aws_iam'
        aws_access_key_id => 'redacted'
        aws_secret_access_key => 'redacted'
        region => 'us-east-2'
      }
      index => "prod-logs-v1-%{+YYYY.MM}"
      template => "/etc/logstash/es-templates/prod-logs-v1.json"
      template_name => 'prod-logs-v1'
      template_overwrite => true
    }
```
5. Error will show up when logstash starts.

**Expected behavior**
Index template should be installed

**Plugins**
logstash-output-opensearch (1.2.0)

**Host/Environment (please complete the following information):**
 - Logstash docker image 
 - Version 8.2.2

**Full Error Message**
```
Failed to install template {:message=>"bad component(expected absolute path component): _template/prod-k8s-default-v1", :exception=>URI::InvalidComponentError, :backtrace=>["/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/uri/generic.rb:771:in `check_path'", "/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/uri/generic.rb:819:in `path='", "/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/uri/generic.rb:193:in `initialize'", "/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/uri/generic.rb:138:in `build'", "/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/uri/http.rb:62:in `build'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch/http_client/manticore_adapter.rb:176:in `sign_aws_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch/http_client/manticore_adapter.rb:154:in `perform_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch/http_client/pool.rb:270:in `perform_request_to_url'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch/http_client/pool.rb:257:in `block in perform_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch/http_client/pool.rb:346:in `with_connection'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch/http_client/pool.rb:256:in `perform_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch/http_client/pool.rb:264:in `block in Pool'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch/http_client.rb:388:in `template_put'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch/http_client.rb:82:in `template_install'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch/template_manager.rb:37:in `install'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch/template_manager.rb:25:in `install_template'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch.rb:412:in `install_template'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch.rb:247:in `finish_register'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/outputs/opensearch.rb:224:in `block in register'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-opensearch-1.2.0-java/lib/logstash/plugin_mixins/opensearch/common.rb:83:in `block in after_successful_connection'"]}
```

### PR DESCRIPTION
**Pull request by nosnilmot**
### Description
Use absolute path for template endpoint ('/_template' instead of '_template')

### Issues Resolved
Fixes #124 
Fixes #144
Resolves this error installing template:
`[2022-06-08T10:02:44,587][ERROR][logstash.outputs.opensearch][devicelogs_http_input] Failed to install template {:message=>"bad component(expected absolute path component): _template/<template name>", :exception=>URI::InvalidComponentError,  ...`

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has documentation added
- [X] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dtaivpp** [comment]
Hey @VijayanB and @jmazanec15 could we get a review of this? Just wanted to see if there was any feedback you had or if it could be merged in.

**Comment by VijayanB** [comment]
@dtaivpp Sure. Will get to it by EOD.

**Comment by VijayanB** [comment]
Looks like CI is failing for different reason. Will look into it first.

**Review by VijayanB — APPROVED** [review]
LGTM. Thanks for contribution.

**Comment by VijayanB** [comment]
@dblock Can you take a look at this PR? Thanks

**Review by VachaShah — APPROVED** [review]
Thank you @nosnilmot for this fix!

**Pull request merged**
