### PR TITLE
Add gem's public key to repo for cert verification

### PR DESCRIPTION
**Pull request by VijayanB**
Signed-off-by: Vijayan Balasubramanian <balasvij@amazon.com>
### Description
This gem is cryptographically signed. To be sure the gem you install hasn’t been tampered with:
Add certs/opensearch-rubygems.pem (if you haven’t already) as a trusted certificate
```
gem cert --add <(curl -Ls certs/opensearch-rubygems.pem)
gem install logstash-output-openserach -P HighSecurity
```
The HighSecurity trust profile will verify signed gems, and allow only if all the dependencies are signed.
This is created by following https://guides.rubygems.org/security/#building-gems
### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has documentation added
- [X] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by jmazanec15 — COMMENTED** [review]
@VijayanB Could you describe how the certificate was generated?

**Comment by VijayanB** [comment]
> @VijayanB Could you describe how the certificate was generated?



> @VijayanB Could you describe how the certificate was generated?

@jmazanec15 I updated the commit message but forgot to update PR description. Will update it now.

**Review by jmazanec15 — COMMENTED** [review]
@VijayanB How did you validate that this works?

**Comment by VijayanB** [comment]
> @VijayanB How did you validate that this works?

If we don't add cert and install with HighSecurity it will fail.  I tested this manually and works
```
gem install logstash-output-opensearch -P HighSecurity
ERROR:  While executing gem ... (Gem::Security::Exception)
    unsigned gems are not allowed by the High Security policy
```
After adding certs
```
gem install logstash-output-opensearch -P HighSecurity
Successfully installed logstash-output-opensearch-1.0.0-java
1 gem installed
```

**Review by jmazanec15 — APPROVED** [review]

**Pull request merged**
