### PR TITLE
Upgrade logstash-oss to 8.12.1

### LINKED ISSUE #235: Build using logstash >=8.10
**Is your feature request related to a problem? Please describe.**
Yes. As described in https://github.com/elastic/logstash/issues/15908, JRuby 9.3 does not include the necessary Zlib function for processing gzipped S3 log files. The necessary function (`Zlib::GzipReader.zcat()`) exists only in JRuby 9.4. Logstash 8.10 is the first Logstash release to ship with JRuby 9.4.

**Describe the solution you'd like**
Upgrade upstream Logstash to >=8.10

**Describe alternatives you've considered**
Currently I have worked around this problem by modifying the `logstash-input-s3` plugin to shell out to the system `zcat` but that is not ideal for (hopefully) obvious reasons.

**Additional context**
To briefly describe the problem: CloudFront and AWS LBs (and probably other services) concatenate multiple GZipped chunks together into a single GZipped log file. When `Zlib::GZipReader.new` encounters such a file, it reads only the first chunk and then stops, ignoring the rest of the file. The problem is described [in this bug report](https://bugs.ruby-lang.org/issues/9790). As a solution the `zcat` function was added in Ruby 3.

### PR DESCRIPTION
**Pull request by eherot**
### Description
Upgrade upstream logstash-oss to 8.12.1

### Issues Resolved
Fixes #235

### Check List
- [ ] New functionality includes testing. -- NA
  - [x] All tests pass -- NA
- [ ] New functionality has been documented. -- NA
  - [ ] New functionality has documentation added -- NA
- [x] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by eherot** [comment]
@dblock done

**Review by dblock — APPROVED** [review]

**Review by dblock — APPROVED** [review]

**Comment by dlvenable** [comment]
@eherot , Thank you for this contribution!

**Comment by eherot** [comment]
@dblock Yes! I’m not much of a Ruby expert but I am happy to help out as much as I can…

**Comment by dblock** [comment]
Cool, hopefully the existing maintainers @dlvenable & friends notice ;)

In the meantime don't hesitate to pickup anything from https://github.com/opensearch-project/logstash-output-opensearch/issues!

**Pull request merged**
